### ISSUE TITLE
Data used for pretraining

### ISSUE THREAD

**Issue by gchaperon** [wasiahmad/PLBART#1]
hi!

thanks a lot for your contribution!

I was wondering how exactly did you obtain the pretraining Java source code used in the paper. I read that it comes from the github_repos dataset in bigquery.

Is it just all Java files found in the dataset or did you perform some kind of preprocessing, like removing duplicates (forks and such)?

Thanks in advance!
Gabriel.

**Comment by wasiahmad** [comment]
Yes, we first download all Java code via Google BigQuery (as described [here](https://github.com/facebookresearch/TransCoder#little-guide-to-download-github-from-google-big-query)) and then perform preprocessing to extract functions (and other information, e.g., docstring, comments, etc.). For preprocessing, please read instructions [here](https://github.com/facebookresearch/TransCoder#downloadpreprocess-data).

**Comment by gchaperon** [comment]
got it! thanks a lot
