### ISSUE TITLE
translation with indentation

### ISSUE THREAD

**Issue by saichandrapandraju** [wasiahmad/PLBART#13]
Hi,

I want to try translation between **java** and **python**. As current datasets from CodeXGLUE were representing functions in a single line, it is easy to finetune and test. 
But what if I want to do this for **python** where indentation is very important? i.e, how will the tokenization take care of it? 
I saw an example in [TransCoder](https://arxiv.org/pdf/2006.03511.pdf) that they used below format for indentation using `INDENT`, `DEDENT` and `NEWLINE` - 
```
def rm_file ( path ) : NEWLINE try : NEWLINE INDENT os . remove (path) NEWLINE print ( " Deleted " )
DEDENT except : NEWLINE INDENT print ( " Error _ while _ deleting _ file " , path ) DEDENT
```

Can you suggest how to proceed further with indentation using PLBART?

**Comment by saichandrapandraju** [comment]
Figured out that above is possible by using code_tokenizer.py

**Comment by wasiahmad** [comment]
Yes, we follow TransCoder, so during preprocessing, we take care of it.
