### ISSUE TITLE
Would you mind sharing your dictionary?

### ISSUE THREAD

**Issue by whatsmyname** [wasiahmad/PLBART#15]
A very good work!

I want to cite your work via finetuning some downstream tasks based on your pre-trained model.
Would you mind sharing your token dictionary? It will be very helpful for us. :)

**Comment by wasiahmad** [comment]
It is shared here - https://github.com/wasiahmad/PLBART/tree/main/sentencepiece

**Comment by whatsmyname** [comment]
Thank you! :)
