### ISSUE TITLE
About 'cbart' in pretrain/binarize.sh

### ISSUE THREAD

**Issue by LeeSureman** [wasiahmad/PLBART#17]
Hello, I'm trying to run the pretraining experiment of PLBART. But I find that there is a 'cbart' dir in binarize (cbart/sentencepiece.bpe.model), I wonder whether the 'cbart' in the bash file should be replaced by '$SPM_DIR'.

**Comment by wasiahmad** [comment]
Yes, fixed the issue. Thanks for pointing it out.
