### ISSUE TITLE
Why new nl_eval.py always outputs the "0" bleu score?

### ISSUE THREAD

**Issue by LeeSureman** [wasiahmad/PLBART#18]
I run the experiment on code_to_text.
I use the old evaluation "scripts/code_to_text/evaluator.py" and the new evaluation "nl_eval.py" which you just released, and find that the nl_eval.py outputs a 0 bleu score and the old outputs a normal bleu score
![X}T~$XXALT(}4N7PEZ`P21](https://user-images.githubusercontent.com/32452367/128593729-45bc3bd5-5942-4469-ba96-43e02441ef33.png)
![image](https://user-images.githubusercontent.com/32452367/128593740-1222d899-8154-4aad-b749-54ffd4930d25.png)

**Comment by wasiahmad** [comment]
It is a bug, `nl_eval` assumes the gold file is a text file, but in the `code_to_text` task it is a JSON file. Will be fixed shortly.

**Comment by wasiahmad** [comment]
fixed with commit fc1363783c17ccbc5747cb264da577a731965e9c
