### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by wang-weishi** [wasiahmad/PLBART#2]
Thanks to the great contribution in code translation and pre-training area. After reading the related papers (Transcoder and DOBF), we had some clarification questions on the pre-processing procedure of the pre-training corpus built from the Github dataset on google big query. We’d be grateful if you could guide us on these.

- Length of function: are you using any filtering to remove functions above a certain length? If so, what is the threshold length? (token level or any other criteria?)
- Code comment extractor: can you share which libraries or toolkits did you use to do this or did you implement your own comment extractor?
- Do you have any suggestions on extracting bimodal signals (code & description) from the Github dataset? I am feeling that class and class functions are more likely to have NL part (as docstrings).
- Regarding SQL queries that need to be run on the Google bigquery platform (similar to Transcoder’s approach here):
WHERE
NOT c.binary
AND f.path like '%.py'

Should we change this to the below condition to filter out non-function data

WHERE
NOT c.binary
AND file.path LIKE '%.py'
AND name = 'Python'

Thank you so much

**Comment by wasiahmad** [comment]
Hi, sorry for the late response.

1. No, we do not filter out any functions based on a length threshold. However, we truncate the functions during binarizing the data. We set the maximum length to 510. (https://github.com/wasiahmad/PLBART/blob/main/pretrain/binarize.sh#L23)
2. We used the [Transcoder](https://github.com/facebookresearch/TransCoder/tree/master/preprocessing) provided preprocessing code for this purpose. We made some modifications to the preprocessing scripts and you can find our version [here](https://github.com/wasiahmad/PLBART/tree/main/preprocessing). I suggest exploring the [code_tokenizer.py](https://github.com/wasiahmad/PLBART/blob/efe55619f87cbbd24d673cf696247e0d0631befa/preprocessing/src/code_tokenizer.py) and [utils.py](https://github.com/wasiahmad/PLBART/blob/efe55619f87cbbd24d673cf696247e0d0631befa/preprocessing/src/utils.py) scripts.
3. Both types of functions (class or standalone) may have docstrings. You may need to manually check and write some rules to filter out noisy/unhelpful docstrings.
4. I am not sure if we can filter out non-function data. When data is downloaded via Google BigQuery, it is basically all python scripts (if you chose Python language) dumped in files (.json.gz), and then during preprocessing we extract functions (and other information).
