### ISSUE TITLE
about lang token position in the target

### ISSUE THREAD

**Issue by LeeSureman** [wasiahmad/PLBART#20]
I find that in multilingual denoising task of fairseq , the target's language token is at the end, which is not like the table3 in your paper, where the language token is at the start of target. am I wrong? 
![image](https://user-images.githubusercontent.com/32452367/129170734-897369dc-96ab-4ba8-bc7f-c172640444fc.png)

**Comment by LeeSureman** [comment]
I almost figure it out. fairseq will set it as the bos of input in collator.

**Comment by wasiahmad** [comment]
You are right, language token is added at the end of the target sequence. But then fairseq right shift the target sequence by 1 token which brings the language token at the beginning. So, the paper provides the correct information.
