### ISSUE TITLE
Dataset not found when execute `bash run.sh` on code-to-text task

### ISSUE THREAD

**Issue by ztw33** [wasiahmad/PLBART#21]
Hi, I want to train code-to-text model using pretrained model. I download the file `code-to-text.zip`, after I execute `bash prepare.sh`, the files in `data/codeXglue/code-to-text/java` are listed as below:
```shell
.
├── data-bin
│   ├── dict.en_XX.txt
│   ├── dict.java.txt
│   └── preprocess.log
├── test.jsonl
├── test.spm.en_XX
├── test.spm.java
├── train.jsonl
├── train.spm.en_XX
├── train.spm.java
├── valid.jsonl
├── valid.spm.en_XX
└── valid.spm.java
```
When I execute `bash run.sh 0 java`, I got `FileNotFoundError: Dataset not found: valid (/home/.../PLBART/data/codeXglue/code-to-text/java/data-bin)` and `FileNotFoundError: Dataset not found: test (/home/.../PLBART/data/codeXglue/code-to-text/java/data-bin)` error. May I please ask whether I forget some steps? Which files are supposed to be in `data/codeXglue/code-to-text/java`? Sorry if I bother, I appreciate your help!

**Comment by wasiahmad** [comment]
You need to run the [prepare.sh](https://github.com/wasiahmad/PLBART/blob/main/scripts/code_to_text/prepare.sh) script. Since binarization has not been done, there is no `data-bin` folder.

**Comment by ztw33** [comment]
Sorry for bothering again... I said in the issue that I have executed `bash prepare.sh` and I do have `data-bin` folder under `data/codeXglue/code-to-text/java`. But it keeps on telling me `Dataset not found`, I don't know what files are supposed to be in `data-bin` folder.

**Comment by wasiahmad** [comment]
The `java` directory should look as follows. 

```
.
  |-train.spm.java
  |-valid.jsonl
  |-train.spm.en_XX
  |-test.spm.java
  |-test.spm.en_XX
  |-valid.spm.java
  |-valid.spm.en_XX
  |-test.jsonl
  |-train.jsonl
  |-data-bin
  |  |-train.java-en_XX.java.idx
  |  |-valid.java-en_XX.en_XX.bin
  |  |-preprocess.log
  |  |-train.java-en_XX.en_XX.bin
  |  |-valid.java-en_XX.java.idx
  |  |-valid.java-en_XX.en_XX.idx
  |  |-dict.java.txt
  |  |-train.java-en_XX.en_XX.idx
  |  |-test.java-en_XX.en_XX.idx
  |  |-train.java-en_XX.java.bin
  |  |-test.java-en_XX.en_XX.bin
  |  |-dict.en_XX.txt
  |  |-test.java-en_XX.java.idx
  |  |-valid.java-en_XX.java.bin
  |  |-test.java-en_XX.java.bin
```

In the `prepare.sh` script, this [function](https://github.com/wasiahmad/PLBART/blob/main/scripts/code_to_text/prepare.sh#L43) should be executed. Please delete the `data-bin` directory and re-run the `prepare.sh` script.

**Comment by ztw33** [comment]
> The `java` directory should look as follows.
> 
> ```
> .
>   |-train.spm.java
>   |-valid.jsonl
>   |-train.spm.en_XX
>   |-test.spm.java
>   |-test.spm.en_XX
>   |-valid.spm.java
>   |-valid.spm.en_XX
>   |-test.jsonl
>   |-train.jsonl
>   |-data-bin
>   |  |-train.java-en_XX.java.idx
>   |  |-valid.java-en_XX.en_XX.bin
>   |  |-preprocess.log
>   |  |-train.java-en_XX.en_XX.bin
>   |  |-valid.java-en_XX.java.idx
>   |  |-valid.java-en_XX.en_XX.idx
>   |  |-dict.java.txt
>   |  |-train.java-en_XX.en_XX.idx
>   |  |-test.java-en_XX.en_XX.idx
>   |  |-train.java-en_XX.java.bin
>   |  |-test.java-en_XX.en_XX.bin
>   |  |-dict.en_XX.txt
>   |  |-test.java-en_XX.java.idx
>   |  |-valid.java-en_XX.java.bin
>   |  |-test.java-en_XX.java.bin
> ```
> 
> In the `prepare.sh` script, this [function](https://github.com/wasiahmad/PLBART/blob/main/scripts/code_to_text/prepare.sh#L43) should be executed. Please delete the `data-bin` directory and re-run the `prepare.sh` script.

Thanks a lot! I have successfully run the training scripts. Thanks again for your patience!
