### ISSUE TITLE
Multilingual `prepare.sh` throws an error after downloading

### ISSUE THREAD

**Issue by gchhablani** [wasiahmad/PLBART#26]
While running `prepare.sh` the followign errors are thrown for all the languages in `multilingual` directory:

```python
FileNotFoundError: [Errno 2] No such file or directory: '/home/crocoder/Desktop/transformers/PLBART/multilingual/data/processed/valid.php-en_XX.php'
Traceback (most recent call last):
  File "encode.py", line 92, in <module>
    main()
  File "encode.py", line 88, in main
    process(args)
  File "encode.py", line 49, in process
    with open(args.input_source, 'r', encoding='utf-8') as f1, \
FileNotFoundError: [Errno 2] No such file or directory: '/home/crocoder/Desktop/transformers/PLBART/multilingual/data/processed/test.php-en_XX.php'
```
Any help on this?

**Comment by gchhablani** [comment]
@wasiahmad Thanks!
I will check again the order in which things are run and get back. My `processed` directory is empty after `download.sh`. Will see what is causing the issue.

**Comment by gchhablani** [comment]
The actual issue was that `libclang-6.0` is needed. Probably a dependency for some package involved.

Doing the following fixed the issue:

```bash
sudo apt-get install -y libclang-6.0-dev
```

**Comment by wasiahmad** [comment]
Ah I see, the tokenizer supports the C++ language too. So, libclang is required. Perhaps, I should remove it since none of the downstream tasks is involved with the C++ language.
