### ISSUE TITLE
fairseq-train: error: argument --task: invalid choice: 'translation_without_lang_token'

### ISSUE THREAD

**Issue by sindhura97** [wasiahmad/PLBART#29]
I am getting this error from fairseq-train: I am trying to run the codexglue translation task.
fairseq-train: error: argument --task: invalid choice: 'translation_without_lang_token'
Can you help me resolve this?

**Comment by sindhura97** [comment]
When I use a previously downloaded fairseq, this error disappears but I now get unrecognized arguments: --langs java,python,en_XX,javascript,php,ruby,go --min-lr -1 while trying to fine-tune plbart-csnet

**Comment by wasiahmad** [comment]
- task `translation_without_lang_token` requires the use of `--user-dir` flag, please check its use.
- `--langs` flag do not work with the task `translation_without_lang_token`. The flag is specific to the `translation_multi_simple_epoch_extended` task.

Please study the use of Fairseq, it will help you to resolve these simple issues easily.
