### ISSUE TITLE
Can PLBART work on single statement?

### ISSUE THREAD

**Issue by kimgimkigi** [wasiahmad/PLBART#31]
Hi, Thanks for sharing the items.

I have a simple question.
In the dataset, most of the data input is a single method declaration paragraph.

But If the input data is single statements, PLBART still works well?

for example, in code-to-code tasks(translate java code to python code),
If we input `System.out.println("hello world");` then PLBART could translate it to `print("hello world")` ?

I'm asking this because I want to use PLBART encoder as statement embedding model.

Thanks!

**Comment by wasiahmad** [comment]
PLBART needs training to be able to do such statement-level translation. You may consider the dataset from [https://github.com/wasiahmad/AVATAR](https://github.com/wasiahmad/AVATAR) to train PLBART and evaluate on such statements.
