### ISSUE TITLE
The experiments of task classification

### ISSUE THREAD

**Issue by vananh0905** [wasiahmad/PLBART#32]
Hi,

Thanks for sharing these interesting works.

When I loaded the best checkpoint to reproduce the results in the defect detection dataset, I got 61.75 ACC. File result.txt in google drive is also 61.78 ACC, while in the paper, the ACC is 63.18.
Is it the best checkpoint?

Thank you so much

**Comment by wasiahmad** [comment]
Read the answer for **Mismatch in performance reported in the paper and achieved using the released checkpoints** from [https://github.com/wasiahmad/PLBART#faqs](https://github.com/wasiahmad/PLBART#faqs).
