### ISSUE TITLE
Can other programming languages be used?

### ISSUE THREAD

**Issue by shaoyangxu** [wasiahmad/PLBART#39]
Hello author, I have two questions:
1. Why do you use java and python?
I see https://github.com/facebookresearch/TransCoder provides pre-processing pipeline for three languages: c++\java\python, so i just want ask why do you just use two of them(java and python)?
2. Can other programming languages be used? 
In this [bigmodel work,](https://github.com/bigscience-workshop/bigscience/blob/9eec76b77e34a21bc239d6e63c59b19aa8161e57/train/tr11-176B-ml/README.md) they use C++, C#, Go, Java, JavaScript, Lua, PHP, Python, Ruby, Rust, Scala, TypeScript for programming languages. However, different programming languages need very different preprocessing pipelines, which is too difficult for me to write language-specific preprocessing code. So, could you recommend some related resources useful for this problem? 
Thx!

**Comment by wasiahmad** [comment]
1. Because Java and Python are the two most popular languages and they are quite different in terms of syntax.
2. You may consider using [tree-sitter ](https://tree-sitter.github.io/tree-sitter/) to build a universal tokenizer to support all your target languages.
