### ISSUE TITLE
Can we add structural information in PLBART?

### ISSUE THREAD

**Issue by smith-co** [wasiahmad/PLBART#44]
I know this is not the perfect question to add into this repo. I understand PLABART is based on a transformer architecture and deal with sequence based text stream.

But would be curious to know whether we can embed structural information like AST level edges in PLBART.

**Comment by wasiahmad** [comment]
We can do anything we want with PLBART; however, what you are looking for is not supported in the code repository.

**Comment by smith-co** [comment]
@wasiahmad how would you actually approach adding AST level edges in PLBART as it is a sequence based model?

**Comment by wasiahmad** [comment]
PLBART uses a Transformer structure. Therefore, you can follow prior works that fused AST info into the Transformer architecture.
