### ISSUE TITLE
plbart-large window size

### ISSUE THREAD

**Issue by alibrahimzada** [wasiahmad/PLBART#49]
I believe there is something wrong with the window size (n_positions) of `plbart-large`. It prints the following:

```
>>> from transformers import PLBartTokenizer
>>> tokenizer = PLBartTokenizer.from_pretrained("uclanlp/plbart-large")
>>> tokenizer.model_max_length
1000000000000000019884624838656
```

I will be statically setting this to `1024`.

**Comment by wasiahmad** [comment]
Can you raise the issue in Huggingface transformers? I do not have knowledge about the `model_max_length` field.

**Comment by alibrahimzada** [comment]
reported issue in HuggingFace.
