### ISSUE TITLE
Can you provide the trained code-to-code-translation model?

### ISSUE THREAD

**Issue by mingzhu0527** [wasiahmad/PLBART#5]
I see only one model checkpoint is released. Can you release the trained code-to-code-translation model also?
Thanks in advance!

**Comment by wasiahmad** [comment]
We have plans to release all the fine-tuned models, but each checkpoint is of size 1.9GB. So, we need some time. I will try to start uploading the checkpoints next week.

**Comment by mingzhu0527** [comment]
Follow up on this. May I know when the model will be released?

**Comment by davidhin** [comment]
+1 any updates on the model checkpoint?

**Comment by wasiahmad** [comment]
We have the translation model checkpoints available here.

- [Java to CS](https://drive.google.com/drive/folders/1OTibmDXrNXcg4an1ehSx1W-JNG5M2kRY?usp=sharing)
- [CS to Java](https://drive.google.com/drive/folders/1_TCQMfGhuS8-DcE-SII8sEbxryEWG3Zx?usp=sharing)

We will gradually release model checkpoints for other tasks too.
