### ISSUE TITLE
Code Summarization using Hugging Face Checkpoints

### ISSUE THREAD

**Issue by ztw33** [wasiahmad/PLBART#54]
I'm attempting to use the checkpoints released on the Hugging Face for code summarization. However, when I utilize the Inference API provided by Hugging Face to generate summaries, the generated summaries are either meaningless or result in "No text was generated".

![py](https://github.com/wasiahmad/PLBART/assets/30229525/bd7f76d3-fb8c-4f71-b9ce-cbfc7c5c7b06)
![java1](https://github.com/wasiahmad/PLBART/assets/30229525/f12094c9-8077-472d-8c5d-19e1ebf6cc46)
![java2](https://github.com/wasiahmad/PLBART/assets/30229525/40889123-644b-4498-b88a-3fbac50985ef)

Is there something wrong with my input? Really appreciate your help!

**Comment by wasiahmad** [comment]
Can you post this in HF? I am not sure what is causing this issue.
