### ISSUE TITLE
The urls of GoogleDrive maybe failed

### ISSUE THREAD

**Issue by martinwz** [wasiahmad/PLBART#55]
Hi, I tried to download PLBART checkpoint. However, the urls of GoogleDrive maybe failed in the download.sh in the pretrain. Would you please provide new urls?
![截图 2024-07-24 19-56-01](https://github.com/user-attachments/assets/0252df44-648c-48a1-81f1-ec05e586b92c)

**Comment by wasiahmad** [comment]
Yes, unfortunately, the checkpoints are no longer available through GDrive. Please get them from Huggingface.
