### ISSUE TITLE
ImportError: cannot import name '_bleu' from 'bleu'

### ISSUE THREAD

**Issue by tmarrakchi** [wasiahmad/PLBART#8]
HI,

I have a problem when I run the "/scripts/text_to_code/run.sh" file. here is the error:

`  File "/content/drive/MyDrive/Colab_Notebooks/PLBART-main/scripts/text_to_code/evaluator.py", line 5, in <module>
    from bleu import _bleu
ImportError: cannot import name '_bleu' from 'bleu' (/usr/local/lib/python3.7/dist-packages/bleu/__init__.py)
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/PLBART-main/evaluation/CodeBLEU/calc_code_bleu.py", line 34, in <module>
    assert len(hypothesis) == len(pre_references[i])
AssertionError`

if it's still a problem with the packages. Can you send me your project requirements.txt file please?

**Comment by wasiahmad** [comment]
Can you check by replacing the following line in the `evaluator.py` script (scripts/text_to_code/evaluator.py)

```
from bleu import _bleu
```

by

```
from evaluation.bleu import _bleu
```

**Comment by tmarrakchi** [comment]
Thanks it works well
